# -*- coding: utf-8 -*-
"""Job seeker & Job matching system

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PvDSGyuXd0vVi5GQC6p2fp7SxDISMJ_B
"""

#Job seekers details

job_seekers = [
    {'Name' : 'Krish', 'Age':30, 'Education': 'Bcom'},
    {'Name' : 'Sanjeev', 'Age':28, 'Education': 'BBA'},
    {'Name' : 'Andrea', 'Age':34, 'Education': 'Btech'}
]

#Candidate skills

sanjeev_skills = ['management skill', 'business development', 'negotiation', 'communication', 'sales']
krish_skills = [  'Financial statement analysis', 'Ledger balances verification', 'MS Excel','Financial Reporting']
andrea_skills = ['Python', 'Java', 'C', 'C++', 'SQL']

#BCom job vacancies

job_vacancies_bcom = [
    {'Title' : 'Audit Associate','Company' :'Deloitte','Education':'Bachelor of Commerce (B.Com)','Required Skills' :['Financial statement analysis', 'Ledger balances verification','MS Excel']},
    {'Title' : 'Junior Accountant','Company' :'Tata Consultancy Services (TCS)','Education':'Bachelor of Commerce (B.Com)','Required Skills' :['Financial statement analysis', 'Ledger balances verification','MS Excel']},
    {'Title' : 'Audit Associate','Company' :'Deloitte','Education':'Bachelor of Commerce (B.Com)','Required Skills' :['General ledger accounting', 'Accounts payable/receivable (AP/AR) processing', 'Bank reconciliation statements (BRS)']}
    ]

#BBA job vacancies

job_vacancies_bba = [
    {'Title' : 'Sales executive','Company' :'HDFC Bank','Education':'BBA','Required Skills' :['Business Development', 'Communication', 'Negotiation']},
    {'Title' : 'Junior BDE','Company' :'Hindustan Unilever','Education':'BBA','Required Skills' :['Sales', 'Negotiation', 'Communication']},
    {'Title' : 'Marketing executive','Company' :'Reliance Industries','Education':'BBA','Required Skills' :['Marketing', 'Communication', 'Market Research']}
    ]

#Btech job vacancies

job_vacancies_btech = [
    {'Title' : 'Python Developer','Company' :'Infosys','Education':'B.Tech','Required Skills' :['Python', 'SQL', 'Git']},
    {'Title' : 'Software Developer','Company': 'Wipro','Education':'B.Tech','Required Skills' :['Java', 'C++', 'SQL']},
    {'Title' : 'Junior Software Engineer','Company' :'Tech Mahindra','Education':'B.Tech','Required Skills' :['C++', 'Java', 'Problem Solving']}
    ]

job_categories = ('Accounting', 'Business', 'Software Development')
education_levels = ('B.Com','BBA','B.Tech')

#Sets creation

andrea_skills_set = set(andrea_skills)
required_skills = ['Python', 'SQL', 'Git']
required_skills_set = set(required_skills)
matching_skills = andrea_skills_set & required_skills_set
print ('Andrea Skills:', andrea_skills_set)
print ('Required Skills:', required_skills_set)
print ('Matching Skills:', matching_skills)

#Finding missing skills

missing_skills = required_skills_set - andrea_skills_set
print ('Missing Skills:', missing_skills)

#Finding all skills

all_skills = required_skills_set | andrea_skills_set
print ('All Skills:',all_skills)

#Finding matching skills

matching_skills = andrea_skills_set & required_skills_set
print ('Matching Skills:', matching_skills )
matching_skills_count = (len(matching_skills))
print ('Matching Skills Count:', matching_skills_count)

#Missing skills count

missing_skills_count = len(missing_skills)
print ('Missing Skills Count:',missing_skills_count)

#Andrea's Skill Count

andrea_skills_count = (len(andrea_skills_set))
print ('Andrea Skills Count:',andrea_skills_count)

#Andre's Skill Match Percentage

andrea_skills_match_percentage = (len(matching_skills) / len(required_skills)) * 100
print ('Andrea Skills Match Percentage:',round(andrea_skills_match_percentage,2))

#Is Andrea Qualified?

if andrea_skills_match_percentage >=70:
  print ('Status:', 'Andrea is highly qualified')
  print ('Skills Match Percentage:', '>=70%')
elif andrea_skills_match_percentage >=50:
   print ('Status:','Andrea is qualified')
   print ('Skills Match Percentage:','>=50%')
else:
   print ('Status:','Andrea is disqualified')
   print ('Skills Match Percentage:','<50%')
print ('Missing Skills:', missing_skills)
print ('Andrea Skills Match Percentage:',round(andrea_skills_match_percentage,2))

#Andrea's Skills Assessment

print ('Andrea Skills:', andrea_skills_set)
print ('Required Skills:', required_skills_set)
print ('Matching Skills:', matching_skills)
print ('Missing Skills:', missing_skills)
print ('Andrea Skills Match Percentage:',round(andrea_skills_match_percentage,2))
status = 'Andrea is qualified'
skills_percentage = '>=50%'
print ('Status:', status)
print ('Skills Percentage:', skills_percentage)

#Candidate details in dictionery

candidate = {'Name': 'Andrea', 'Age':25, 'Role': 'Junior Python Developer', 'Experience':1}
print ('Name:', candidate['Name'])
print ('Age:', candidate['Age'])
print ('Role:',candidate['Role'])
print ('Experience:', candidate['Experience'])

#Modifying a dictionery

updated_age = 27
updated_experience = 2
location = 'Hyderabad'
candidate['Location'] = location
candidate['Age'] = updated_age
candidate['Experience'] = updated_experience
print ('Name:', candidate['Name'])
print ('Updated Age:', candidate['Age'])
print ('Role:',candidate['Role'])
print ('Updated Experience:', candidate['Experience'])
print ('Location:',candidate['Location'])

candidate.pop('Location')

print (candidate)

job_seekers = [
    {'Name' : 'Krish', 'Age':30, 'Education': 'Bcom'},
    {'Name' : 'Sanjeev', 'Age':28, 'Education': 'BBA'},
    {'Name' : 'Andrea', 'Age':34, 'Education': 'Btech'}
]

#Candidate skills

sanjeev_skills = ['management skill', 'business development', 'negotiation', 'communication', 'sales']
krish_skills = [  'Financial statement analysis', 'Ledger balances verification', 'MS Excel','Financial Reporting']
andrea_skills = ['Python', 'Java', 'C', 'C++', 'SQL']

required_skills = ['Python', 'SQL', 'Git']

for job_seeker in job_seekers:
  print (job_seeker['Name'])
  print (job_seeker['Age'])
  print (job_seeker['Education'])

required_skills = ['Python', 'SQL', 'Git']
required_skills_set = set (required_skills)
print (required_skills_set)

job_seekers = [
    {'Name' : 'Krish', 'Age':30, 'Education': 'Bcom', 'Skills':['management skill', 'business development', 'negotiation', 'communication', 'sales']},
    {'Name' : 'Sanjeev', 'Age':28, 'Education': 'BBA', 'Skills':['Financial statement analysis', 'Ledger balances verification', 'MS Excel','Financial Reporting']},
    {'Name' : 'Andrea', 'Age':34, 'Education': 'Btech', 'Skills':['Python', 'Java', 'C', 'C++', 'SQL']}
]

for job_seeker in job_seekers:
  candidate_skills_set = set(job_seeker['Skills'])
  matching_skills_set = candidate_skills_set & required_skills_set
  missing_skills_set = required_skills_set - candidate_skills_set
  len(matching_skills_set)
  len(required_skills_set)
  skills_match_percentage = len(matching_skills_set) / len(required_skills_set) * 100
  print ('Candidate Name', job_seeker['Name'])
  print ('Skills match percentage:', skills_match_percentage)
  print ('Matching skills count:', len(matching_skills_set))
  print ('Required skills count:', len(required_skills_set))
  print ('Matching skills set:', matching_skills_set)
  print ('Missing skills set:', missing_skills_set)

job_seekers = [
    {'Name' : 'Krish', 'Age':30, 'Education': 'Bcom', 'Skills':['management skill', 'business development', 'negotiation', 'communication', 'sales']},
    {'Name' : 'Sanjeev', 'Age':28, 'Education': 'BBA', 'Skills':['Financial statement analysis', 'Ledger balances verification', 'MS Excel','Financial Reporting']},
    {'Name' : 'Andrea', 'Age':34, 'Education': 'Btech', 'Skills':['Python', 'Java', 'C', 'C++', 'SQL']}
]

for job_seeker in job_seekers:
  candidate_skills_set = set(job_seeker['Skills'])
  matching_skills_set = candidate_skills_set & required_skills_set
  missing_skills_set = required_skills_set - candidate_skills_set
  skills_match_percentage = len(matching_skills_set) / len(required_skills_set) * 100

  if skills_match_percentage >=70:
    Status = 'Qualified'
  elif skills_match_percentage >=50:
    Status = 'Partially Qualified'
  else:
    Status = 'Disqualified'
  print ('Candidate Name', job_seeker['Name'])
  print ('Status:', Status)

job_seekers = [
    {'Name' : 'Krish', 'Age':30, 'Education': 'Bcom', 'Skills':['management skill', 'business development', 'negotiation', 'communication', 'sales']},
    {'Name' : 'Sanjeev', 'Age':28, 'Education': 'BBA', 'Skills':['Financial statement analysis', 'Ledger balances verification', 'MS Excel','Financial Reporting']},
    {'Name' : 'Andrea', 'Age':34, 'Education': 'Btech', 'Skills':['Python', 'Java', 'C', 'C++', 'SQL']}
]
def assess_candidate(job_seeker):
    candidate_skills_set = set(job_seeker['Skills'])
    matching_skills_set = candidate_skills_set & required_skills_set
    missing_skills_set = required_skills_set - candidate_skills_set
    skills_match_percentage = len(matching_skills_set) / len(required_skills_set) * 100

    if skills_match_percentage >=70:
      Status = 'Qualified'
    elif skills_match_percentage >=50:
      Status = 'Partially Qualified'
    else:
      Status = 'Disqualified'
    job_seeker['Status'] = Status
    print ('Candidate Name', job_seeker['Name'])
    print ('Status:', Status)

for job_seeker in job_seekers:
  assess_candidate(job_seeker)

